### PR TITLE
Add Mathematica 11.3.0 英文版 磁力链接

### PR DESCRIPTION
**Pull request by arisaka97**
- 这份磁链对应的种子文件是我做的，文件名为：Mathematica 11.3 with Keygen (Win&Linux&Mac)
- Wolfram Research 从这个版本开始，Windows 版和 Mac 版官网只提供下载器。种子文件中的 Linux 版安装文件是从官网下载的，Windows 版是用官方下载器下载的，Mac 版由于官方下载器下载速度实在太慢，挂代理都没用，于是使用了网盘资源。
- **三个安装包均在对应的环境下测试过了，都可以成功安装并激活**。测试环境分别为：Windows 10，openSuSE Leap 42.3，macOS 10.11
- 种子文件已经上传至海盗湾（thepiratebay.org），在我的 VPS 上做种已超过36小时(截至 18-03-24 02:24 CST)，但下载来源多在境外。国内的话，希望吧主可以协助做种（下载全部的文件，并保持BT客户端开启即可，以便持续上传）。
- 百度云在我们学校的网络环境下限速严重，以后我会尽早提供 BT 种子。

### CODE REVIEW

**Comment by CNMan** [comment]
11.3
```
File Name:  CDFPlayer_11.3.0_WIN_DM.exe
File Name:  gridMathematica_11.3.0_LightweightGridManager_WIN.iso
File Name:  gridMathematica_11.3.0_LightweightGridManager_WIN_DM.exe
File Name:  Mathematica_11.3.0_Chinese_WIN.iso
File Name:  Mathematica_11.3.0_Chinese_WIN_DM.exe
File Name:  Mathematica_11.3.0_Japanese_WIN.iso
File Name:  Mathematica_11.3.0_Japanese_WIN_DM.exe
File Name:  Mathematica_11.3.0_Japanese_WIN_LabVersion.iso
File Name:  Mathematica_11.3.0_Japanese_WIN_LabVersion.zip
File Name:  Mathematica_11.3.0_WIN.iso
File Name:  Mathematica_11.3.0_WIN_DM.exe
File Name:  Mathematica_11.3.0_WIN_LabVersion.iso
File Name:  Mathematica_11.3.0_WIN_LabVersion.zip

File Name:  CDFPlayer_11.3.0_LINUX.sh
File Name:  gridMathematica_11.3.0_LightweightGridManager_LINUX.iso
File Name:  gridMathematica_11.3.0_LightweightGridManager_LINUX.sh
File Name:  Mathematica_11.3.0_Japanese_LINUX.iso
File Name:  Mathematica_11.3.0_Japanese_LINUX.sh
File Name:  Mathematica_11.3.0_LINUX.iso
File Name:  Mathematica_11.3.0_LINUX.sh
File Name:  Mathematica_11.3.0_LINUX_LabVersion.iso
File Name:  Mathematica_11.3.0_LINUX_LabVersion.sh

File Name:  CDFPlayer_11.3.0_MAC_DM.dmg
File Name:  gridMathematica_11.3.0_LightweightGridManager_MAC_DM.dmg
File Name:  Mathematica_11.3.0_Chinese_MAC_DM.dmg
File Name:  Mathematica_11.3.0_Japanese_MAC_DM.dmg
File Name:  Mathematica_11.3.0_Japanese_MAC_LabVersion.dmg
File Name:  Mathematica_11.3.0_MAC_DM.dmg
File Name:  Mathematica_11.3.0_MAC_LabVersion.dmg
```
|文件名|MD5SUM|SHA1SUM|
|-------------|-------------|-------------|
|Mathematica_11.3.0_Chinese_MAC_DM.dmg|ea2e74e84e501fdcd17301e7e8779d16|d76a0bcc1d39f9ec834f804aa8a2b35d2d65c894|
|Mathematica_11.3.0_Chinese_WIN.iso|dbadfd4439202609ef174a9fb2a28536|5bd7f98f4bf6fefce20494c182468bb8c3037a7f|
|Mathematica_11.3.0_Chinese_WIN_DM.exe|0b1f5b54fea88fad3a719cc5d6b4853b|9ba9021156a1031ed43576a05a39434145e65e4a|
|Mathematica_11.3.0_LINUX.iso|d656e7c69dbf284e95b36121a2b374cb|150bc0e2f2f9f56917f546cb2e6b10627f7685f0|
|Mathematica_11.3.0_LINUX.sh|c772e916922ff95f04a0dad5aa2f6d5f|02cf954b5090d58438e2d1f187f9599bcad92f98|
|Mathematica_11.3.0_LINUX_LabVersion.iso|f2fd05f289f7d481861d090154f0da99|c3cf19810e15447f03630c84f095a90fa3bbfbee|
|Mathematica_11.3.0_LINUX_LabVersion.sh|28f0c290e8287fd71cc2b1878519196e|29591c40c006e002849907d45b458340a4240576|
|Mathematica_11.3.0_MAC_LabVersion.dmg|b55e81385e469b8e6212ef5606bb3616|9ae74b9878d43128e2fddd2844a4b8c2299e0b6a|
|Mathematica_11.3.0_WIN.iso|f2e97dbc37bd7c0eea796c7366e04399|634976fb164a99a4630e65a391e2e0ecb6a1cbf0|
|Mathematica_11.3.0_WIN_LabVersion.iso|12a85c39f4b358904a5d6ca81df41c10|2c0d4bbcdcadec78c5c8d88317aad6e6081f3bce|
|Mathematica_11.3.0_WIN_LabVersion.zip|d16109a7e67dac2bc0ea905556a46522|3a2f00056a26199a0f6542fe9118bf68d30624af|

11.2 中文版

|文件名|MD5SUM|SHA1SUM|
|-------------|-------------|-------------|
|Mathematica_11.2.0_Chinese_MAC.dmg|b55381e5eb58a81bcf8f5e5ddf991b69|bb5842b42c943aea4aca0ea7b50e110d155fd374|
|Mathematica_11.2.0_Chinese_WIN.iso|eafaaad0d5f6f51e918bdfe56f8f4708|249a79dfbd0e8b6d9fd9082faa4c0f5098978716|
|Mathematica_11.2.0_Chinese_WIN.zip|282fe2e587c7e48414cc8cdd79e8647d|0a6e21f9ce7620dba656402169d81f3a72c1656d|

10.4.1
```
File Name:  CDFPlayer_10.4.1_WIN.exe
File Name:  gridMathematica_10.4.1_LightweightGridManager_WIN.iso
File Name:  gridMathematica_10.4.1_LightweightGridManager_WIN.zip
File Name:  Mathematica_10.4.1_Chinese_WIN.iso
File Name:  Mathematica_10.4.1_Chinese_WIN.zip
File Name:  Mathematica_10.4.1_Japanese_WIN.iso
File Name:  Mathematica_10.4.1_Japanese_WIN.zip
File Name:  Mathematica_10.4.1_Japanese_WIN_LabVersion.iso
File Name:  Mathematica_10.4.1_Japanese_WIN_LabVersion.zip
File Name:  Mathematica_10.4.1_WIN.iso
File Name:  Mathematica_10.4.1_WIN.zip
File Name:  Mathematica_10.4.1_WIN_LabVersion.iso
File Name:  Mathematica_10.4.1_WIN_LabVersion.zip

File Name:  CDFPlayer_10.4.1_LINUX.sh
File Name:  gridMathematica_10.4.1_LightweightGridManager_LINUX.iso
File Name:  gridMathematica_10.4.1_LightweightGridManager_LINUX.sh
File Name:  Mathematica_10.4.1_Japanese_LINUX.iso
File Name:  Mathematica_10.4.1_Japanese_LINUX.sh
File Name:  Mathematica_10.4.1_LINUX.iso
File Name:  Mathematica_10.4.1_LINUX.sh
File Name:  Mathematica_10.4.1_LINUX_LabVersion.iso
File Name:  Mathematica_10.4.1_LINUX_LabVersion.sh

File Name:  CDFPlayer_10.4.1_OSX.pkg
File Name:  gridMathematica_10.4.1_LightweightGridManager_OSX.dmg
File Name:  Mathematica_10.4.1_Chinese_OSX.dmg
File Name:  Mathematica_10.4.1_Japanese_OSX.dmg
File Name:  Mathematica_10.4.1_Japanese_OSX_LabVersion.dmg
File Name:  Mathematica_10.4.1_OSX.dmg
File Name:  Mathematica_10.4.1_OSX_LabVersion.dmg
```
|文件名|MD5SUM|SHA1SUM|
|-------------|-------------|-------------|
|Mathematica_10.4.1_Chinese_OSX.dmg|c9ad09347dd5006cdb54b960a8459786|4101cda866b07b624b635bf40eacc36a2b0bb64e|
|Mathematica_10.4.1_Chinese_WIN.iso|c28beecc6ff8ef6ce342355a67b06f74|73281fb55078668d4772c63f7ef517d93a6f20a1|
|Mathematica_10.4.1_Chinese_WIN.zip|f1fc423b055c4d0579e58b2031cb72dd|f714fb3c60d139ec4e0679a607078873e80e310e|
|Mathematica_10.4.1_LINUX.iso|0e168f689035def20849396cabdc1c86|ddaa56fd9aabc5ba7efa14d42e7d061b972f362f|
|Mathematica_10.4.1_LINUX.sh|ea1f13a88279e6fc2ed1edc80e7a1612|a22e81bd99236fd5e5787ce0f243e1fa95338092|
|Mathematica_10.4.1_LINUX_LabVersion.iso|2163ed2ed66704d407f992d1447c9953|807ad0e799c6899dd1c91b87caf3781ae55f02d0|
|Mathematica_10.4.1_LINUX_LabVersion.sh|da92ccd8e9174c357a177472d8a4ddc2|27170bce34fba4e6f386dac1da4ff9723f50569e|
|Mathematica_10.4.1_OSX.dmg|2bdb0cf7313712396b8591d0d1ec50bf|63ead0ef32fe05a8271a743e6ccea8276699300b|
|Mathematica_10.4.1_OSX_LabVersion.dmg|bc7573ecebd6ac1ac6c12896ccc6d540|1f3995678cb041908c4d611d359047310ba030de|
|Mathematica_10.4.1_WIN.iso|1ee96e04e948c00d2d408bf5e60efdd5|1a59e039c860e4ad44aa8688fda2ec70e6d5f0d3|
|Mathematica_10.4.1_WIN.zip|29191d315d6b4e7beef358088c801a71|567d51be17103c15c0377814720f9b082f32ac71|
|Mathematica_10.4.1_WIN_LabVersion.iso|96f19cc1d8b9e4a75736e640a094405e|5fea68ae7f8123d952999bd86478fdf4c92170e7|
|Mathematica_10.4.1_WIN_LabVersion.zip|e27431b4337b631af06710ee518db339|e7b9900257fc986dc4196ccfef151767a7d1710a|

9.0.1
```
File Name:  CDFPlayer_9.0.1_WIN.exe
File Name:  gridMathematica_9.0.1_LightweightGridManager_WIN.EXE
File Name:  gridMathematica_9.0.1_LightweightGridManager_WIN.iso
File Name:  Mathematica_9.0.1_Chinese_WIN.EXE
File Name:  Mathematica_9.0.1_Chinese_WIN.iso
File Name:  Mathematica_9.0.1_Japanese_WIN.exe
File Name:  Mathematica_9.0.1_Japanese_WIN.iso
File Name:  Mathematica_9.0.1_Japanese_WIN_LabVersion.exe
File Name:  Mathematica_9.0.1_Japanese_WIN_LabVersion.iso
File Name:  Mathematica_9.0.1_WIN.exe
File Name:  Mathematica_9.0.1_WIN.iso
File Name:  Mathematica_9.0.1_WIN_LabVersion.iso
File Name:  Mathematica_9.0.1_WIN_Universal.exe
File Name:  PlayerPro_9.0.1_WIN.exe

File Name:  CDFPlayer_9.0.1_LINUX.sh
File Name:  gridMathematica_9.0.1_LightweightGridManager_LINUX.iso
File Name:  gridMathematica_9.0.1_LightweightGridManager_LINUX.sh
File Name:  Mathematica_9.0.1_Japanese_LINUX.iso
File Name:  Mathematica_9.0.1_Japanese_LINUX.sh
File Name:  Mathematica_9.0.1_LINUX.iso
File Name:  Mathematica_9.0.1_LINUX.sh
File Name:  Mathematica_9.0.1_LINUX_LabVersion.iso
File Name:  Mathematica_9.0.1_LINUX_Universal.sh
File Name:  PlayerPro_9.0.1_LINUX.sh

File Name:  CDFPlayer_9.0.1_OSX.dmg
File Name:  gridMathematica_9.0.1_LightweightGridManager_OSX.dmg
File Name:  Mathematica_9.0.1_Chinese_OSX.dmg
File Name:  Mathematica_9.0.1_Japanese_OSX.dmg
File Name:  Mathematica_9.0.1_Japanese_OSX_LabVersion.dmg
File Name:  Mathematica_9.0.1_OSX.dmg
File Name:  Mathematica_9.0.1_OSX_Universal.dmg
File Name:  PlayerPro_9.0.1_OSX.dmg
```
|文件名|MD5SUM|SHA1SUM|
|-------------|-------------|-------------|
|Mathematica_9.0.1_Chinese_OSX.dmg|ab071e21cb1ed0831b4981eb1f990997|fa7195f167bb33dd154d699aaabc78e9bbd573c1|
|Mathematica_9.0.1_Chinese_WIN.EXE|76c33fecdeffaef88d30c4acde170da4|6412d0e0069cf2fa93986842491b44ab103b0767|
|Mathematica_9.0.1_Chinese_WIN.iso|8e5eeb6f35507890b3a24cc2c76706b9|632a84a71898bb5b6c1112c9a44b189e5c8a3afb|
|Mathematica_9.0.1_LINUX.iso|4ae563c25e02c3979e90384aa6b884ed|60a80f415e699171289a7757c3fcd27e07021d53|
|Mathematica_9.0.1_LINUX.sh|7fcbc4d1488757b10ef07740ac30a580|b38a7ac82e038aeed93f49c85303a39fef484cb8|
|Mathematica_9.0.1_LINUX_LabVersion.iso|db56d7be78983117479c549dd5c831cd|ead7b6de3fa8f16fb0ba7304c5ab9b23ec346861|
|Mathematica_9.0.1_LINUX_Universal.sh|0346072e77027db475ec93464158f690|75a6ddfd20dcbf440af8f4bb1e588629cc7be3c1|
|Mathematica_9.0.1_OSX.dmg|edd30f8ea005ea57e2c3c99dc2177155|be1c206a5a8c6aa0ee00356584069e73cc0c6f1c|
|Mathematica_9.0.1_OSX_Universal.dmg|db4c76a9d817b59939a512786d78f3b5|0ca2875f3ddcffe7262ec4edda4dd83e8f489b15|
|Mathematica_9.0.1_WIN.exe|e19f28eb42abca2ca577b1ff4c74ceb2|f2307c9060913bd5d19772d35860413d001b9553|
|Mathematica_9.0.1_WIN.iso|0246ca281c49760fcf7ac234c4382d56|6f852b9d117cbe4332c2ea8dee751fde0d9f4242|
|Mathematica_9.0.1_WIN_LabVersion.iso|9607e19f3f00a4d1d6139a11c21375d2|3706bc39c8d70c22785332eb0a0e5e5df6e6e642|
|Mathematica_9.0.1_WIN_Universal.exe|de855d4f96334ed46d522b371d7f079d|837d2e081a44dc891762eb19b905294041eb9c8f|

**Comment by CNMan** [comment]
11.3.0中文版win只有iso了，zip格式的变下载器了，mac的dmg格式也是下载器
[Mathematica_11.3.0_Chinese_MAC_DM.zip](https://github.com/TieBaMma/InstallTutorial/files/1873269/Mathematica_11.3.0_Chinese_MAC_DM.zip)
[Mathematica_11.3.0_Chinese_WIN_DM.zip](https://github.com/TieBaMma/InstallTutorial/files/1873271/Mathematica_11.3.0_Chinese_WIN_DM.zip)

**Comment by CNMan** [comment]
[贴吧](https://tieba.baidu.com/mo/q---3C8BDC6B13A40063E8EE835193ADBB22%3AFG%3D1--1-3-0--2--wapp_1523706982227_536/m?kz=5646252913&is_bakan=0&lp=5010&pinf=1_2_10)有人求这个，发在这里吧，我没贴吧账号
[MLinkforExcel_3.7.1_WIN.zip](https://github.com/TieBaMma/InstallTutorial/files/1910460/MLinkforExcel_3.7.1_WIN.zip)

**Comment by arisaka97** [comment]
@CNMan 你好，请问你是否拥有你列出的文件本身或者下载地址？比如 LabVersion.iso 文件，我想知道这是什么版本，因为在别处没有见过，谢谢。

**Comment by CNMan** [comment]
@arisaka97 有的，不过不方便共享，看官网的意思是给无网络连接的实验室安装的
http://support.wolfram.com/kb/14697

**Comment by MathMapMat** [comment]
@CNMan 请问能分享LightweightGridManager的Win/Mac/Linux文件或者其下载器（我假定DM结尾的是下载器）吗？Wolfram官网说免费提供，但是我买的License输进去没反应。谢谢！

**Comment by Single34** [comment]
11.3.0好像有一次更新。

**Comment by Single34** [comment]
不知道 @CNMan 你有没有其他中间版本的MD5SUM？比如10.0.1,10.0.2之类的。

**Pull request merged**
